// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Notify() {
  return window['go']['main']['App']['Notify']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
